### ISSUE TITLE
Support networkmanager

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/aws-source#315]
# Network Manager

We need to support AWS network manager resources so that we can determine the potential implications of changes to these resources.

This source works alongside all of the other AWS sources that we have developer so far to map the infrastructure in an AWS account. An example of an extremely simple source can be found [here](https://github.com/overmindtech/source-template). However this AWS sources is quite a lot more complicated, to make it simpler we have created a number of generic structs such as [`AlwaysGetSource`](https://github.com/overmindtech/aws-source/blob/main/sources/always_get_source.go#L34) that remove a lot of the duplication that you would usually have to do. For each of the resource types below you will need to:

* Work out which generic should be used (`AlwaysGetSource`, `DescribeOnlySource` or `GetListSource`)
* Populate that generic with all of the basic info
* Research the item and work out which other AWS resources it can reasonably be linked to, for example an EC2 instance has a Security Group, which we [create links for](https://github.com/overmindtech/aws-source/blob/main/sources/ec2/instance.go#L412-L430), then create all of these links using our existing [naming conventions](https://github.com/overmindtech/aws-source?tab=readme-ov-file#naming-conventions)
* Create tests as described below

## Resources

Below are the describe methods for all the resources we will need to support. Each of these will need the following:

* A source created e.g. https://github.com/overmindtech/aws-source/blob/main/sources/ec2/capacity_reservation.go
* [Smart comments](https://github.com/overmindtech/aws-source/blob/main/sources/ec2/capacity_reservation.go#L94-L101) to allow for automatic documentation
* [Linked item queries](https://github.com/overmindtech/aws-source/blob/main/sources/ec2/capacity_reservation.go#L71-L83) for all things the resource could reasonably be linked to
* [Smart comments for each possible link](https://github.com/overmindtech/aws-source/blob/main/sources/ec2/capacity_reservation.go#L70)
* Tests that include
  * [Realistic sample data](https://github.com/overmindtech/aws-source/blob/main/sources/ec2/capacity_reservaion_test.go#L15-L46)
  * [Expected links](https://github.com/overmindtech/aws-source/blob/main/sources/ec2/capacity_reservaion_test.go#L68-L87)

---

### Phase 1

Pine one of the below, have a go and raise a PR for review

* [x] [ResourcePolicy](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetResourcePolicy)
* [x] [Site](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetSites)
* [x] [GlobalNetwork](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.DescribeGlobalNetworks)
* [x] [VPCAttachment](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetVpcAttachment)

### Phase 2

Do another 3-5 and raise another PR just to make sure you're on the right course. From then do it however you want until they're complete

* [ ] [TransitGatewayRouteTableAttachment](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetTransitGatewayRouteTableAttachment)
* [ ] [TransitGatewayRegistration](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetTransitGatewayRegistrations)
* [ ] [TransitGatewayPeering](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetTransitGatewayPeering)
* [ ] [TransitGatewayConnectPeerAssociation](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetTransitGatewayConnectPeerAssociations)
* [ ] [SiteToSiteVpnAttachment](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetSiteToSiteVpnAttachment)
* [ ] [NetworkResource](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetNetworkResources)
  * https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetNetworkResourceRelationships
* [ ] [Link](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetLinks)
  * [ ] https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager@v1.19.2/types#LinkAssociation
* [ ] [Device](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetDevices)
* [ ] [CoreNetworkPolicy](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetCoreNetworkPolicy)
* [ ] [CoreNetwork](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetCoreNetwork)
* [ ] [Connection](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetConnections)
* [ ] [ConnectPeer](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetConnectPeer)
  * [ ] [ConnectPeerAssociation](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetConnectPeerAssociations)
* [ ] [ConnectAttachment](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/networkmanager#Client.GetConnectAttachment)
