### ISSUE TITLE
Support SQS

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/aws-source#374]
SQS is one of the most popular AWS services and we need to support it. A large number of AWS services can be configured to send events over SQS queues so it's very likely that these resources will form an important part of linking together all the pieces of an application. In fact there are also [some examples](https://github.com/overmindtech/aws-source/blob/65edc13c1e9722280ca6d3655760f5419ecd274b/sources/s3/s3.go#L463-L482) of links that have already been created to SQS queues in anticipation of this source being created. In order for these to all work we need to ensure that we follow the [naming convention](https://github.com/overmindtech/aws-source?tab=readme-ov-file#naming-conventions)

Seems from the [docs](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sqs) that basically the only type here will be a queue. You can list them using [`ListQueues`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sqs#Client.ListQueues) and then you'll need to get the details of each using [`GetQueueAttributes`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sqs#Client.GetQueueAttributes)

**Tasks:**

* [x] Implement SQS queue
* [x] Check if there are any other types that we need
* [ ] Contact @dylanratcliffe to add the required new permissions to the IAM role as this is a new service
